# Project information
site_name: Arduino Firmware Uploader
site_description: A firmware uploader/updater for Arduino Boards.
site_url: https://arduino.github.io/arduino-fwuploader/

# Repository
repo_name: arduino/arduino-fwuploader
repo_url: https://github.com/arduino/arduino-fwuploader
edit_uri: ""

# Copyright
copyright: Copyright 2021 ARDUINO SA (http://www.arduino.cc/)

# Theme
theme:
  name: material
  logo: img/icon_mac_light.png
  palette:
    primary: teal
    accent: orange

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: arduino
      repo: arduino-fwuploader
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true

# Navigation
nav:
  - Documentation Home: README.md
  - Command reference:
    - arduino-fwuploader: commands/arduino-fwuploader.md
    - certificates: commands/arduino-fwuploader_certificates.md
    - certificates flash: commands/arduino-fwuploader_certificates_flash.md
    - firmware: commands/arduino-fwuploader_firmware.md
    - firmware flash: commands/arduino-fwuploader_firmware_flash.md
    - firmware list: commands/arduino-fwuploader_firmware_list.md
    - version: commands/arduino-fwuploader_version.md
