[tool.poetry]
name = "FirmwareUploader"
version = "0.0.0"
description = "FirmwareUploader"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "6.1.2"
invoke = "^1.5.0"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.5b1"

[tool.black]
line-length = 120
target-version = ["py38"]