[tool.poetry]
name = "FirmwareUploader"
version = "0.0.0"
description = "FirmwareUploader"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "6.1.2"
invoke = "^1.5.0"
semver = "^2.13.0"
