name: Generate Index

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    branches:
      - umbynos/index_generation
  push:
    paths:
      - "generator/**"
      - "firmwares/**"
      - "poetry.lock"
      - "pyproject.toml"
  workflow_dispatch:
  repository_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: generator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/setup-task@v1

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platforms
        run: |
          arduino-cli core update-index -v
          arduino-cli version
          arduino-cli core install arduino:samd@${{ env.SAMD_V }} -v
          arduino-cli core install arduino:megaavr@${{ env.MEGAAVR_V }} -v
          arduino-cli core install arduino:mebd_nano@${{ env.MBED_NANO_V }} -v
        env:
          SAMD_V: 1.18.11
          MEGAAVR_V: 1.8.7
          MBED_NANO_V: 2.2.0

      - name: Install dependencies
        run: task poetry:install-deps

      - name: Generate index
        run: ./generator.py -a $(which arduino-cli)

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --import --batch --passphrase ${{ secrets.PASSPHRASE }} private.key

      - name: sign the json
        run: gpg --output boards/module_firmware_index.json.sig --detach-sign boards/module_firmware_index.json

      - name: create the gzip
        run: gzip --keep boards/module_firmware_index.json

      - name: s3 sync
        run: ./s3Copy.sh . s3://arduino-downloads-prod-beagle/arduino-fwuploader
