name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  native-os-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: ["386", "arm"]
        exclude:
          - os: macos-latest
            node: "386"
          - os: macos-latest
            node: "arm"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Build native
        shell: bash
        run: task build

      - name: Cross-build
        shell: bash
        run: GOARCH=${{ matrix.arch }} task build

      - name: Run unit tests
        run: task test
